---
title: "CSAS2025"
output: html_document
date: "2025-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(Rforestry)
library(tidyr)
library(splines)
source("X_RF_OLS.R")
```

## Simulation 1

```{r sim1}
#' Fixed treatment effect
################################################################################
# Simulation 1
################################################################################
# Treatment effect is constant
g1 <- function(t, w){
  return(omega + b1*(t - tm)^2 + b2*(t - tm)^2*(t > tm) + b3*(t - tm)^3*(t > tm) + 2*w)
}

f1 <- function(x, t, w){
  return(rnorm(1, 0 , s_gamma) + bi*(t - tm)^2*(t > tm))
}

getY1 <- function(x, t){
  wi <- rbinom(N, 1, 0.133)
  Yi <- g1(t, wi) + f1(x, t, wi) + rnorm(N, 0, sig_e)
  return(list(Y = Yi, W = wi))
}

tm <- 25; b1 <- -1/9; b2 <- -6/1000; b3 <- 45/10000; sig_b <- 0.02; sig_e <- 1
N <- 1000; omega <- 0; s_gamma <- 0.4;
bi <- rnorm(N, 0, sig_b)
Y <- getY1(x, 30)
lt <- seq(18, 40)
lall <- list()
i <- 1
for (t in lt){
  Y1 <- getY1(x, t)
  dft <- data.frame(player = factor(seq(1, N)), age = t, w = Y1$W,y = Y1$Y)
  lall[[i]] <- dft
  print(dim(dft))
  i <- i + 1
}

dfF <- do.call(rbind, lall)
# Remove players without overlap
dfF <- ungroup(dfF %>% group_by(player) %>% filter(any(w == 0) && any(w==1)))
dfF <- data.frame(dfF)


dfg <- dfF %>% group_by(age, w) %>% reframe(average = g1(age, w), sd = sd(y), 
                                              .groups = "drop")
# Create a ribbon plot
gg <- ggplot(dfg, aes(x = age, y = average, fill = as.factor(w), color = as.factor(w))) +
  geom_ribbon(aes(ymin = average - sd, ymax = average + sd), alpha = 0.3, color = NA) +
  geom_line(size = 1) +
  scale_color_manual(
    values = c("0" = "maroon", "1" = "royalblue4"),
    labels = c("Control", "Treatment"),
    name = "Group"
  ) +
  scale_fill_manual(
    values = c("0" = "brown1", "1" = "turquoise"),
    labels = c("Control", "Treatment"),
    name = "Group"
  ) +
  labs(
    x = "Age",
    y = "Value"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 11),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

ggsave(filename = paste0("../output/Image/Simulation1.pdf"), plot = gg,
       device = 'pdf')
gg
saveRDS(dfF, "../data/simulations1.rds")
```

## Simulation 2

```{r sim2}

################################################################################
# Simulation 2
################################################################################
#' Treatment effect depends on age
g1 <- function(t, w){
  return(omega + b1*(t - tm)^2 + b2*(t - tm)^2*(t > tm) + b3*(t - tm)^3*(t > tm) + 1/10*(t - 18)*w)
}

f1 <- function(x, t, w){
  return(rnorm(1, 0 , s_gamma) + bi*(t - tm)^2*(t > tm))
}

getY1 <- function(x, t){
  wi <- rbinom(N, 1, 0.133)
  Yi <- g1(t, wi) + f1(x, t, wi) + rnorm(N, 0, sig_e)
  return(list(Y = Yi, W = wi))
}

bi <- rnorm(N, 0, sig_b)
Y <- getY1(x, 30)
lt <- seq(18, 40)
lall <- list()
i <- 1
for (t in lt){
  Y1 <- getY1(x, t)
  dft <- data.frame(player = factor(seq(1, N)), age = t, w = Y1$W,y = Y1$Y)
  lall[[i]] <- dft
  i <- i + 1
}

dfF <- do.call(rbind, lall)
# Remove players without overlap
dfF <- ungroup(dfF %>% group_by(player) %>% filter(any(w == 0) && any(w==1)))
dfF <- data.frame(dfF)


dfg <- dfF %>% group_by(age, w) %>% reframe(average = g1(age, w), sd = sd(y), 
                                            .groups = "drop") 

gg <- ggplot(dfg, aes(x = age, y = average, fill = as.factor(w), color = as.factor(w))) +
  geom_ribbon(aes(ymin = average - sd, ymax = average + sd), alpha = 0.3, color = NA) +
  geom_line(size = 1) +
  scale_color_manual(
    values = c("0" = "maroon", "1" = "royalblue4"),
    labels = c("Control", "Treatment"),
    name = "Group"
  ) +
  scale_fill_manual(
    values = c("0" = "brown1", "1" = "turquoise"),
    labels = c("Control", "Treatment"),
    name = "Group"
  ) +
  labs(
    x = "Age",
    y = "Value"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 11),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
gg
ggsave(filename = paste0("../output/Image/Simulation2.pdf"), plot = gg,
       device = 'pdf')
saveRDS(dfF, "../data/simulations2.rds")
```

## Simulation 3

```{r}
################################################################################
# Simulation 3
################################################################################
#' Treatment effect depends on age and there is confounding and high imbalance
g1 <- function(t, w){
  return(omega + b1*(t - tm)^2 + b2*(t - tm)^2*(t > tm) + b3*(t - tm)^3*(t > tm) + 
           (2*(t - 16) + 0.0005*(t > 20)*(t - tm)^3 - 0.0005*(t > tm)*(t - tm)^4)*w)
}

f1 <- function(x, t, w){
  return(rnorm(1, 0 , s_gamma) + bi*(t - tm)^2*(t > tm) - w*x*5/(1+exp(-(t - 25))))
}

getY1 <- function(x, t){
  wi <- rbinom(N, 1, 0.01)
  xi <- runif(N, -1, 1)
  Yi <- g1(t, wi) + f1(xi, t, wi) + rnorm(N, 0, sig_e)
  return(list(Y = Yi, W = wi, D = xi))
}

bi <- rnorm(N, 0, sig_b)
Y <- getY1(x, 30)
lt <- seq(18, 40)
lall <- list()
i <- 1
for (t in lt){
  Y1 <- getY1(x, t)
  dft <- data.frame(player = factor(seq(1, N)), age = t, w = Y1$W,y = Y1$Y, defence = Y1$D)
  lall[[i]] <- dft
  i <- i + 1
}

dfF <- do.call(rbind, lall)
# Remove players without overlap
dfF <- ungroup(dfF %>% group_by(player) %>% filter(any(w == 0) && any(w==1)))
dfF <- data.frame(dfF)

dfg <- dfF %>% group_by(age, w) %>% reframe(average = g1(age, w), sd = sd(y), 
                                            .groups = "drop")
gg <- ggplot(dfg, aes(x = age, y = average, fill = as.factor(w), color = as.factor(w))) +
  geom_ribbon(aes(ymin = average - sd, ymax = average + sd), alpha = 0.3, color = NA) +
  geom_line(size = 1) +
  scale_color_manual(
    values = c("0" = "maroon", "1" = "royalblue4"),
    labels = c("Control", "Treatment"),
    name = "Group"
  ) +
  scale_fill_manual(
    values = c("0" = "brown1", "1" = "turquoise"),
    labels = c("Control", "Treatment"),
    name = "Group"
  ) +
  labs(
    x = "Age",
    y = "Value"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 11),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
gg
ggsave(filename = paste0("../output/Image/Simulation3.pdf"), plot = gg,
       device = 'pdf')
saveRDS(dfF, "../data/simulations3.rds")
```



















## Evaluation
```{r}

sim <- 1
dfF <- readRDS(paste0("../data/simulations", as.character(sim), ".rds"))

# Add splines
nspline <- 5
spline <- ns(dfF$age, df = nspline)
dfns <- data.frame(ns(dfF$age, df = nspline))
spcols <- paste0("NS", seq(1,nspline))
colnames(dfns) <- paste0("NS", seq(1,nspline))
dfF <- cbind(dfF, dfns)

# Estimation
po <- "y"; trt <- "w"
x_data <- dfF[, !(names(dfF) %in% c(po, trt, "age"))]; y_data <- dfF[, po]; 
w_data <- dfF[, trt]

smodel.ols <- s.ols(x_data, w_data, y_data)
s.cates.ols <- s.est.ols(smodel.ols, x_data)

tmodel.ols <- t.ols(x_data, w_data, y_data)
t.cates.ols <- t.est.ols(tmodel.ols, x_data)

xmodel.ols <- x.ols(x_data, w_data, y_data)
x.cates.ols <- x.est.ols(xmodel.ols, x_data)

smodel.rf <- s.rf(x_data, w_data, y_data)
s.cates.rf <- s.est.rf(smodel.rf, x_data)

tmodel.rf <- t.rf(x_data, w_data, y_data)
t.cates.rf <- t.est.rf(tmodel.rf, x_data)

xmodel.rf <- x.rf(x_data, w_data, y_data)
x.cates.rf <- x.est.rf(xmodel.rf, x_data)

cates <- cbind(s.cates.ols, t.cates.ols, x.cates.ols, s.cates.rf, t.cates.rf, x.cates.rf)
colnames(cates) <- c('s.cates.ols', 't.cates.ols', 'x.cates.ols', 's.cates.rf', 
                     't.cates.rf', 'x.cates.rf')

dfF <- cbind(dfF,cates)
if (sim == 1){
  dfF$cate.oracle <- 2
} else if (sim == 2){
  dfF$cate.oracle <- 1/10*(dfF$age - 18)
} else if (sim == 3){
  # dfF$cate.oracle <- 1/3*(dfF$age - 25)
  t <- dfF$age; tm <- 25
  dfF$cate.oracle <- (2*(t - 16) + 0.0005*(t > 20)*(t - tm)^3 - 0.0005*(t > tm)*(t - tm)^4)
}

# Reshape the data to long format
df_long <- dfF %>%
  pivot_longer(cols = contains("cate"), names_to = "variable", values_to = "value")

df.cate <- df_long %>%
  group_by(age, variable) %>%
  summarise(value = mean(value), .groups = "drop") 

# Create a plot
ggplot(df.cate, aes(x = age, y = value, group = variable, color = variable)) +
  geom_line(alpha = 0.7) +  # Adjust width for spacing
  labs(x = "Age", y = "Value") +
  theme_minimal() +
  scale_color_manual(values = c("purple", "brown1", "dodgerblue", "brown2", "steelblue", "brown3", "mediumblue"))

# Calculate MSE
df_diff <- dfF %>%
  select(matches("cate")) %>%
  transmute(across(everything(), ~(. - dfF$cate.oracle)^2, .names = "mse.{.col}"))
df_diff$age <- dfF$age

df_long <- df_diff %>%
  pivot_longer(cols = contains("mse."), names_to = "variable", values_to = "value")
df.mse <- df_long %>%
  group_by(age, variable) %>%
  summarise(value = mean(value), .groups = "drop") 

df.mse <- df.mse %>%
  filter(variable != "mse.cate.oracle")

gg <- ggplot(df.mse, aes(x = age, y = value, group = variable, color = variable)) +
  geom_line(size = 1, alpha = 0.8) +
  scale_color_manual(
    values = c("brown1", "dodgerblue", "maroon", 
               "steelblue", "brown3", "mediumblue"),
    name = "Model"
  ) +
  labs(
    x = "Age",
    y = "Value"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top",
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 10),
    axis.title = element_text(face = "bold")
  )

print(gg)

#ggsave(filename = paste0("output/Image/mse_simulation", as.character(sim), ".pdf"), plot = gg,
#       device = 'pdf')

df.mse.agg <- df_long %>%
  group_by(variable) %>%
  summarise(value = mean(value), .groups = "drop") 
write.csv(df.mse.agg, paste0("output/mse_simulation", as.character(sim), ".csv"))
print(df.mse.agg[order(df.mse.agg$value),])
```

## Excersice
1. Calculate the loss function for simulation 2 and 3. What do you expect?
2. Modify S,T, and X learner to use other ML models. Can you achieve lower MSE for specific simulations?




